import Head from 'next/head';
import { Header, List } from '@/components';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title> Coinsgrate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Header />
       <List data={data} />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&page=1&sparkline=false&price_change_percentage=24h%2C7d');
  return {
    props:{
      data: data ? await data.json() : [],
    }
  }
}
